accelerate launch src/train_bash.py \
    --ddp_timeout 18000000 \
    --stage sft \
    --do_train \
    --model_name_or_path /data/models/WizardCoder-Python-34B-V1.0 \
    --dataset python-evol \
    --template default \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir saves/wizard/lora \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --fp16